name: CI Test

on: pull_request

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build VEX project
      uses: schineaj23/vex-build@v1.0
      with:
        path: /home/runner/work/vex2019-20/vex2019-20/V5
