name: CI Test

on: pull_request

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build VEX project
      uses: AritroSaha10/vex-build@v1.1-beta.6
      with:
        path: V5/
    - name: Run make command
      uses: AritroSaha10/build-make-project@v0.2-alpha
      with:
        path: V5/
      
  
